; *************************************************
; *************************************************
; ******* File generated by Extruder Turtle *******
; ******* written by Leah Buechley and  ***********
; ******* and Franklin Pezutti-Dyer ***************
; ******* Hand and Machine Lab, UNM, 2022 *********
; *************************************************
; *************************************************
; *************** Printer parameters **************
; Printer: 3D Potter Super
; Nozzle size: 3.0
; Extrude width: 3.4
; Layer height: 2.2
; Extrude rate: 3.0
; Speed: 1000
; *************** 3D Potter initialization **************
M82                             ; Absolute extrusion mode
G28                             ; Home all axes
G92 E0                          ; Reset Extruder
G90 							; Absolute coordinates for X,Y,Z   
; M208 X0 Y0 Z0 S1              ; Set axis minima
; M208 X415 Y405 Z500 S0        ; Set axis maxima 
G1 X202.5 Y202.5 Z25 F10000 	; Go to the starting position (center of bed) 25mm above print
G1 F20000 E2000                 ; Prime Extruder, Extrude 2000mm of clay
G1 X202.5 Y202.5 Z0 F1000 		; Go to the starting position more slowly
M83                             ; Relative extrusion
G91                     		; Relative coordinates for X,Y,Z axes
G1 E5                 			; Extrude 5mm of clay
G1 F1000
; *************** End printer initialization **************
; *************** End of print **************
G1 F5000 Z20            ; Move extruder above print 50mm 
G90                     ; Absolute coordinates  
G1 F5000 X0 Y0          ; Move extruder to 0,0 in XY
M104 S0                 ; Cool down hotend
M140 S0                 ; Cool down bed
M107                    ; Turn off fan
M84                     ; Disable motors
