; *************************************************
; *************************************************
; ******* File generated by Extruder Turtle *******
; ******* written by Leah Buechley and  ***********
; ******* and Franklin Pezutti-Dyer ***************
; **** Hand and Machine Lab, UNM, 2021-present ****
; *************************************************
; *************************************************
; *************** Matrix initialization **************
G28
G90                     		; Absolute coordinates for X,Y,Z axes
G0 F2000 X1000.0 Y1000.0 Z200 	; Move to starting position
M83 							; Relative extrustion
G91                     		; Relative coordinates for X,Y,Z axes
G1 F1000
; ********** End printer initialization ***********
; *************************************************

; ***************** Print parameters **************
; Nozzle size: 20.0
; Extrude width: 10.0
; Layer height: 10.0
; Extrude rate: 10.0
; Speed: 1000
; Mix Factor: 0.9
; *************************************************

G1 X50.0 Y0.0 E500.0
G1 X-25.0 Y-43.3013 E500.0
G1 X-25.0 Y43.3013 E500.0
; *************** End of print ***************
G91                     ; Relative coordinates for X,Y,Z axes
G1 Z25 F2000            ; move up 25 in the z direction
G90                     ; Absolute coordinates 
G1 F5000 X0 Y0          ; Move extruder to 0,0 in XY
M84 X Y                 ; X Y steppers off
M104 S0					; Set Hot-end to 0C (off)
M140 S0					; Set bed to 0C (off)
