import Rhino.Geometry as geom
import rhinoscriptsyntax as rs
import ExtruderTurtle as e
import operator as op
import math
import random
import extruder_turtle
import slicer_utilities as su
from extruder_turtle import *

# takes a shape as input and slices with WeaveSlicer, using wall width and wavelength
# input: shape to slice, file to write gcode to, and slicing parameters 
# calls weave_slice_turtle
# output: generated path for visualization in Rhino
def weave_slice (shape, file=False, layer_height=1.0, wall_width=3.0, wavelength=3.0, mode=1, bottom_layers=0, skin=False):
	t = ExtruderTurtle()
	if (file):
		t.setup(filename=file, printer = "eazao")
	else:
		t.setup(printer = "eazao")
	print("WARNING: Slicing for the eazao printer. If you need different slicing parameters, use the weave_slice_turtle function.")
	t.write_gcode_comment("You can replace everything above this line with the correct header for your 3D printer.")
	t.set_layer_height(layer_height)
	t.penup()
	weave_slice_turtle(t,shape,wall_width=wall_width,wavelength=wavelength, mode=mode, bottom_layers=bottom_layers, skin=skin)
	t.finish()
	return t.get_lines()

# The main function, does the work of slicing and generating gcode
# takes a turtle + a shape as input and slices with WeaveSlicer, using wall width and wavelength
# input: turtle (.gcode file associted with turtle), shape to slice, and slicing parameters 
# output: list of layers
def weave_slice_turtle (t,shape,wall_width=3.0,wavelength=3.0, mode=1, bottom_layers=0, skin=False):
	t.write_gcode_comment("**************************************************")
	t.write_gcode_comment("******* file generated by WeaveSlicer ************")
	t.write_gcode_comment("******* conception: Camila Friedman-Gerlicz ******")
	t.write_gcode_comment("****** python implementation: Leah Buechley ******")
	t.write_gcode_comment("************** 2023 - present ********************")
	t.write_gcode_comment("**************************************************")
	layer_height = t.get_layer_height()
	shape_slices = su.slice_shape(shape,layer_height=layer_height)
	layers = []

	# for all slices in shape
	for i in range(0,len(shape_slices)):
		x,points = weave_one_slice_turtle(t=t,layer=i,shape=shape,wall_width=wall_width,wavelength=wavelength, mode=mode, bottom_layers=bottom_layers, skin=skin, shape_slices=shape_slices)
		layers.append(x)

	return layers,points


# takes a turtle, shape, and layer number as input and slices that layer with WeaveSlicer, using wall width and wavelength
# input: turtle (.gcode file associted with turtle), layer number, shape to slice, and slicing parameters 
# output: sliced layer
def weave_one_slice_turtle (t,layer,shape,wall_width=3.0,wavelength=3.0, mode=1, bottom_layers=0, skin=False, shape_slices=False):
	# print("layer: " +str(layer))
	layer_height = t.get_layer_height()
	original_speed = t.get_speed()
	original_extrude = t.get_extrude_rate()
	if (shape_slices==False):
		shape_slices = su.slice_shape(shape,layer_height=layer_height)
	if (layer%2==0):
		offset=True
	else:
		offset=False
	k=0
	i = layer
	layers = []
	skin_offset_factor = .6

	# if top layer:
	if (layer==len(shape_slices)-1): 
		slice0 = shape_slices[i-1][k] # previous slice
		slice1 = shape_slices[i][k] # current slice
		if (skin==True):
			point = rs.CurveAreaCentroid(slice0)[0]
			slice0 = rs.OffsetCurve(slice0,point,t.get_extrude_width()*skin_offset_factor)[0]
			point = rs.CurveAreaCentroid(slice1)[0]
			slice1 = rs.OffsetCurve(slice1,point,t.get_extrude_width()*skin_offset_factor)[0]
		points,points1,angles = find_points_and_angles(slice0,slice1,wavelength,wall_width=wall_width,mode=mode,layer=i)
		if (points and points1 and angles):
			interior_points, exterior_points, x=weave_points_and_angles(t,points1,points1,angles,slice1,slice1,wall_width=wall_width,mode=mode,offset=offset, top=True,skin=skin)
			if (skin==True):
				generate_skin(t,points=exterior_points, skin_offset_factor=skin_offset_factor,offset=offset)
		else:
			x = -1

		return x,points1

	# all other layers
	while (k<len(shape_slices[i])):
	# for all branches in current slice
		slice0 = shape_slices[i][k] # current slice
		original_slice = slice0

		if (len(shape_slices[i])==1):
			# if there is just one branch, use slice above to compute angles
			slice1 = shape_slices[i+1][k] # slice above
		else:
			# if there is more than one branch, lift pen and find the slice above
			t.penup()
			# if a branch is closing there may not be a matching branch above
			if (len(shape_slices[i+1])>k):
			# if there is a matching branch above:
				# try easy guess first
				slice1 = shape_slices[i+1][k] # slice above
			else:
			# if there is no matching branch above
				# find closest slice because you have to
				index = su.find_closest_slice(slice0,shape_slices[i+1]) 
				slice1 = shape_slices[i+1][index] # next slice
		
		if (skin==True):
			point = rs.CurveAreaCentroid(slice0)[0]
			slice0 = rs.OffsetCurve(slice0,point,t.get_extrude_width()*skin_offset_factor)[0]
			point = rs.CurveAreaCentroid(slice1)[0]
			slice1 = rs.OffsetCurve(slice1,point,t.get_extrude_width()*skin_offset_factor)[0]

		points,points1,angles = find_points_and_angles(slice0,slice1,wavelength,wall_width=wall_width,mode=mode,layer=i)
		count=0
		while (angles is not False and angles[0]>85 and angles[0]<95 and count<5):
			# if the angle is close to 90
			# a co-planar slice was found
			# this is probably the wrong one, try to find a better one
			index = su.find_closest_slice(slice0,shape_slices[i+1]) 
			slice1 = shape_slices[i+1][index] # next slice
			points,points1,angles = find_points_and_angles(slice0,slice1,wavelength,wall_width=wall_width,mode=mode,layer=i)
			count+=1
		if (points is not False and angles is not False):
			interior_points, exterior_points, x=weave_points_and_angles(t,points,points1,angles,slice0,slice1,wall_width=wall_width,mode=mode,offset=offset,skin=skin)
		else:
			x=-1
		# add skin on as an additional layer to exterior of form
		if (skin==True):
			generate_skin(t,points=exterior_points, skin_offset_factor=skin_offset_factor,offset=offset)


		if (i<bottom_layers and rs.IsCurveClosed(slice0)):
			print("bottom layer: " +str(i))
			if (skin==True):
				t.penup()
			if (interior_points):
				bottom_curve = rs.AddCurve(interior_points)
				bottom_curve = rs.CloseCurve(bottom_curve)
			else:
				bottom_curve = slice0
			point = rs.CurveAreaCentroid(slice0)[0]
			if (mode==1):
				bottom_curve = rs.OffsetCurve(bottom_curve,point,t.get_extrude_width()/2)[0]
			elif(mode==3):
				try:
					if (t.get_printer() is not ("lutum")):
						bottom_curve = bottom_curve
					else:
						bottom_curve = rs.OffsetCurve(bottom_curve,point,t.get_extrude_width()/2)[0]
				except:
					print("offset failed")
					bottom_curve = slice0
			t.set_speed(original_speed*.8)
			su.bottom_layer(t,bottom_curve) 
			t.set_speed(original_speed)
			t.penup()
			t.set_position_point(points[0])

		if (x==-1):
			print("error at index: " +str(i))
		else:
			layers.append(x)
		# t.pendown()

		k+=1

	t.penup()
	if (rs.IsCurveClosed(slice1)==False or rs.IsCurveClosed(slice0)==False): # if current or next curve is not closed, lift pen
		t.penup()

	return x,points

# generates a skin curve based on a curve or list of points
def generate_skin(t,curve =False, points=False, skin_offset_factor=1,offset=False):
	original_speed = t.get_speed()
	if (curve==False and points==False):
		print("Skin error")
		return -1
	if (points):
		skin_curve = rs.AddCurve(points)
	point = rs.CurveAreaCentroid(skin_curve)[0]
	skin_curve = rs.OffsetCurve(skin_curve,point,-t.get_extrude_width()*skin_offset_factor)[0]
	t.set_speed(original_speed/2)
	t.penup()
	if (offset):
		su.follow_curve(t,skin_curve)
	else:
		su.follow_curve(t,skin_curve,reverse=True)
	t.set_speed(original_speed)

# finds points that will be woven. based on wavelength
# finds overhang angle at each point, based on angle between slice0 and slice1
# returns lists of points and angles 
def find_points_and_angles(slice0, slice1, wavelength, mode=1, wall_width=3.0, layer=False, skin=False, num_oscillations=False):
	resolution = wavelength/4.5 # start with a slightly smaller resolution than you want
	# if slice0 is closed and slice1 is open, slice1 is begining of hole and can't find all angles
	# if slice0 is significantly longer than slice1, also can't find all angles
	# in these cases, swap slice0 and slice1 to calculate angles
	swapped_layers = False

	if (mode==3):
		# use a curve offset by wallwidth to calculate number of points for mode 3
		# decreases number of points
		offset_slice = su.get_offset_curve (slice0, wall_width/2)
		try:
			points = rs.DivideCurveEquidistant(offset_slice, resolution) # create points resolution apart to find correct #
		except Exception as e:
			print(e)
			points = rs.DivideCurveEquidistant(slice0, resolution)
	else:
		points = rs.DivideCurveEquidistant(slice0, resolution) # create points resolution apart to find correct #
	point_number = len(points)
	if (point_number/4<3):
		print("skipping very small layer")
		print("points: " +str(point_number))
		print("oscillations: " +str(round(point_number/4,1)))
		return False, False, False

	# if (layer!=0):
	# 	if (num_oscillations is not False):
	# 		resolution = rs.CurveLength(slice0)/(num_oscillations*4)
	# 		points = DivideCurveEquidistant(slice0, resolution)
	# 		point_number = len(points)

	oscillation_change = 8
	# if (oscillation_change>4):
	# 	print("Will change wavelengths after a " +str(oscillation_change) + " oscillation shift in size. In mm: " +str(oscillation_change*wavelength))
	while (point_number%(oscillation_change*4)!=0): #want %4 number of points to complete circle
		point_number-=1
	if (point_number<=12):
		print("small layer, adjusting point number to at least 4 oscillations")
		point_number = 16
	
	# if (point_number0==point_number):
	# 	print("Changing number of oscillations after a " +str(oscillation_change) + " oscillation shift. In mm: " +str(oscillation_change*wavelength))
	# 	# print("old wavelength: " +str(wavelength) + " new wavelength: " +str(round(rs.CurveLength(slice0)*4/point_number,1)))
	points0 = rs.DivideCurve(slice0, point_number)
	points1 = rs.DivideCurve(slice1, point_number) 

	if (point_number<=0):
		return False, False, False;
	print("oscillations in layer " +str(layer) +": " +str(round(point_number/4,1)))
	# print("given wavelength: " +str(wavelength) + " new wavelength: " +str(round(rs.CurveLength(slice0)*4/point_number,1)))
	print("new wavelength: " +str(round(rs.CurveLength(slice0)*4/point_number,1)))
	
	# check for discontinuity between two curves
	slice0_closed = rs.IsCurveClosed(slice0)
	slice1_closed = rs.IsCurveClosed(slice1)
	length_difference = rs.CurveLength(slice1)-rs.CurveLength(slice0)
	if (slice0_closed and not(slice1_closed)): 
		# if slice0 is closed and slice1 is open, slice1 is begining of hole and can't find all angles
		# if slice0 is significantly longer than slice1, also can't find all angles
		# in these cases, swap slice0 and slice1 to calculate angles
		slice_placeholder = slice0
		slice0 = slice1
		slice1 = slice_placeholder
		points0 = rs.DivideCurve(slice0, point_number)
		points1 = rs.DivideCurve(slice1, point_number) 
		swapped_layers = True
	
	angles=[]
	for j in range(0,len(points0)):
		# compare against closest point on next layer
		# assumption: this is the point directly above the current point
		closest=rs.CurveClosestPoint(slice1, points0[j])
		point1 = rs.EvaluateCurve(slice1, closest)
		vector = rs.VectorSubtract(point1,points0[j])
		if (swapped_layers):
			# calculating angles based on layer below
			angle = rs.VectorAngle([0,0,-1.0],vector)
		else:
			# calculating angles based on layer above
			angle = rs.VectorAngle([0,0,1.0],vector)
		angles.append(angle)

	if (swapped_layers): 
		# set points back to correct values for layer
		print("swapping layers back")
		slice_placeholder = slice0
		slice0 = slice1
		slice1 = slice_placeholder
		points0 = rs.DivideCurve(slice0, point_number)
		points1 = rs.DivideCurve(slice1, point_number)

	# check for extreme angles that need correction
	new_points0=[]
	new_points1=[]
	new_angles=[]
	extreme_angles = False
	for j in range (0,len(points0)):
		if (angles[j]>65):
			# in case of extreme angle
			area0 = rs.CurveArea(slice0)[0]
			area1 = rs.CurveArea(slice1)[0]
			percentage_change = abs((area1-area0)/area0)
			# print("percentage change: " +str(percentage_change))
			# big change in area means extreme angle across entire shape
			if (j%8==0 and percentage_change>=.4 and False):
				print("removing some points from extreme angle")
				# remove every third point and angle from list
				extreme_angles = True
				# don't append points and angles to list
			else:
				new_points0.append(points0[j])
				new_points1.append(points1[j])
				new_angles.append(angles[j])
		else:
			try:
				new_points0.append(points0[j])
				new_points1.append(points1[j])
				new_angles.append(angles[j])
			except Exception as e:
				print("error! couldn't append point")
				print(e)

	if (extreme_angles):
		# print("changing points")
		points0=new_points0
		points1=new_points1
		angles=new_angles
		point_number = len(points0)
		# get back to correct number of points
		while (point_number%4!=0): #want %4 number of points to complete circle
			point_number-=1
		points0 = rs.DivideCurve(slice0, point_number)
		points1 = rs.DivideCurve(slice1, point_number) 

	return points0,points1,angles


# generates woven path from points and angles
# calculates amplitude of oscillation based on angles
# writes gcode file with woven path for the given slice (slice0, angles, points)
# returns a list of interior points (inside of zig zag), exterior points (outside zig zag), and layer path
def weave_points_and_angles(t,points,points1,angles,slice0,slice1,wall_width=3.0,mode=1,offset=False,top=False, skin=False):

	if (not(points) or not(points1) or not(angles)):
		return -1

	if (top):
		slice0=slice1
		points=points1

	t2 = ExtruderTurtle()

	# check direction of curve points and adjust if necessary
	t2.set_position_point(points[0])
	t2.set_position_point(points[1])
	t2.left(90)
	t2.forward(1)
	point = t2.get_position()
	slice0_closed = rs.IsCurveClosed(slice0)
	if (slice0_closed):
		test = rs.PointInPlanarClosedCurve(point, slice0)
		if (test==False):
			# point is outside
			# should be inside, swap modes
			if (mode==3):
				mode=2
			elif (mode==2):
				mode=3

	# give turtle correct heading by folloing two points
	t2.set_position_point(points[len(points)-1])
	t2.set_position_point(points[0])

	# t3 will create the slice for this layer and return it as a path
	t3 = ExtruderTurtle()
	t3.penup()
	
	if (not(slice0_closed)):
		# open curve
		t.penup()
		t.set_position_point(points[0])
		t3.penup()
		t3.set_position_point(points[0])
	else:
		# closed curve
		# t.penup() # lifts pen for layer movement
		t.set_position_point(points[0])
		t3.set_position_point(points[0])
		# t.pendown()

	interior_points = []
	exterior_points = []


	# for all points in the slice
	# 4 points per oscillation: in, middle, out, middle
	for j in range(0,len(points)):
		# it is possible, if you're using angles from the prior slice 
		# that you have more points than you have angles
		# if this is the case, don't update the angle variable
		if (j<len(angles)): 
			angle = angles[j]	

		amplitude = ((wall_width/2.0)/math.cos(math.radians(angle)))
		amplitude = small_curve_check(slice0,amplitude,mode)

		if (skin==True):
			original_amplitude=amplitude
			amplitude = amplitude-t.get_extrude_width()/2

		t2.set_position_point(points[j])
		if (offset==True):
			o=j+2
		else:
			o=j
		# interior point
		if (o%4==0):
			if (mode==1): #path should be on curve
				t2.left(90)
				p0 = t.get_position()
				t2.forward(amplitude)
				p1 = t2.get_position()
				if (check_intersection(t3,rs.AddLine(p0,p1))==False):	
					t.set_position_point(t2.get_position())
					t3.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude)
				t2.right(90)
			elif(mode==2): #path should be outside curve
				t.set_position_point(t2.get_position())
				t3.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
			elif(mode==3): #path should be inside curve
				t2.set_position_point(points[j])
				t2.left(90)
				t2.left(6) # hack correction for tight curves
				p0 = t.get_position()
				t2.forward(amplitude*2)
				p1 = t2.get_position()
				if (check_intersection(t3,rs.AddLine(p0,p1))==False):	
				# if (True):
					t.set_position_point(t2.get_position())
					t3.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude*2)
				t2.right(6) # hack correction for tight curves
				t2.right(90)
			else:
				print("MODE ERROR")
				return
			interior_points.append(t.get_position())
		# middle point
		if (o%4==1 or o%4==3):
			if (mode==1): #path should be on curve
				t.set_position_point(t2.get_position())
				t3.set_position_point(t2.get_position())
			elif(mode==2): #path should be outside curve
				t2.right(90)
				t2.forward(amplitude)
				t.set_position_point(t2.get_position())
				t3.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude)
				t2.left(90)
			elif(mode==3): #path should be inside curve
				# don't draw middle point
				t2.set_position_point(t2.get_position())
			else:
				print("MODE ERROR")
				return
		# exterior point
		if (o%4==2):
			if (mode==1): #path should be on curve
				t2.right(90)
				t2.forward(amplitude)
				t.set_position_point(t2.get_position())
				t3.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude)
				t2.left(90)
			elif(mode==2): #path should be outside curve
				t2.right(90)
				t2.forward(amplitude*2)
				t.set_position_point(t2.get_position())
				t3.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude*2)
				t2.left(90)
			elif(mode==3): #path should be inside curve
				# t2 will be on outside of curve
				t2.set_position_point(points[j])
				t.set_position_point(t2.get_position())
				t3.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
			else:
				print("MODE ERROR")
				return
			exterior_points.append(t.get_position())

		if (j<1 and rs.IsCurveClosed(slice0)==False):
			t.penup()
			t3.penup()
		else:
			t.pendown()
			t3.pendown()

	# if the curve is closed, close the curve
	if (slice0_closed==True):
		if (offset):
			t.set_position_point(points[0])
			t3.set_position_point(points[0])
		else:
			t.set_position_point(point0)
			t3.set_position_point(point0)
		interior_points.append(interior_points[0])
		exterior_points.append(exterior_points[0])
	return interior_points, exterior_points, t3.get_lines()

def check_intersection(t,curve):
	turtle_path = t.get_points()
	if (len(turtle_path)<2):
		return False
	t_curve = rs.AddCurve(turtle_path)
	try:
		# intersection_events = rs.CurveCurveIntersection(t_curve, curve)
		intersection_events = 0
		# print(intersection_events)
		if (intersection_events):
			print("found intersection")
			return True
		else:
			return False
	except Exception as e:
		print(e)
		return False

def small_curve_check(slice, amplitude, mode):

	area = rs.CurveArea(slice)

	if (not(area)):
		#if curve is open
		return amplitude

	if(mode==3):
		multiplier=.48
	else:
		multiplier=.9

	area = area[0]
	threshold_amp = math.sqrt(area/math.pi)*multiplier

	if (amplitude>threshold_amp):
		print("adjusted amplitude for small curve")
		new_amplitude = threshold_amp
		return new_amplitude
	else:
		return amplitude

#########################################################################
# WeaveSlicer pattern functions
#########################################################################
# relies on a printer with 2 independent extruders
#########################################################################

def weave_points_and_angles_pattern(t,pattern_row,points,points1,angles,slice0,slice1,wall_width=3.0,mode=1,offset=False,top=False, skin=False, skin_points=False, skip_glass=False, reverse=False):
	speed = t.get_speed()
	if (not(points) or not(points1) or not(angles)):
		return -1

	if (top):
		slice0=slice1
		points=points1

	t2 = ExtruderTurtle()

	# check direction of points and mode
	t2.set_position_point(points[0])
	t2.set_position_point(points[1])
	t2.left(90)
	t2.forward(1)
	point = t2.get_position()
	slice0_closed = rs.IsCurveClosed(slice0)
	if (slice0_closed):
		test = rs.PointInPlanarClosedCurve(point, slice0)
		if (test==False):
			# point is outside
			# should be inside, swap modes
			if (mode==3):
				mode=2
			elif (mode==2):
				mode=3

	t2.set_position_point(points[len(points)-1])

	if (not(slice0_closed)):
		# open curve
		t.penup()
		t.set_position_point(points[0])
	else:
		# closed curve
		t.penup()
		t.set_position_point(points[0])
		t.pendown()


	ratio = len(pattern_row)/len(points)

	#clay part of layer
	t.set_extruder(0)
	pattern_check=False

	# woven part of clay layer
	for j in range(0,len(points)):
		if (j<len(angles)): 
			angle = angles[j]	

		amplitude = (wall_width/2.0)/math.cos(math.radians(angle))
		amplitude = small_curve_check(slice0,amplitude,mode)

		pattern_index = int(round(j*ratio,1))
		if (pattern_row[pattern_index]>.9):
			if (t.get_pen()==False): # beginning of pattern
				t.set_position_point(points[j])
			t.pendown()
			t.set_speed(speed)
		else:
			if (t.get_pen()==True): # end of pattern
				t.set_position_point(points[j])
			t.penup()
			t.set_speed(speed*2)
			amplitude=0
			pattern_check = True
		t2.set_position_point(points[j])
		if (offset==True):
			o=j+1
		else:
			o=j
		if (o%2==0):
			if (mode==1): #path should be on curve
				t2.left(90)
				t2.forward(amplitude)
				t.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude)
				t2.right(90)
			elif(mode==2): #path should be outside curve
				t2.right(90)
				t2.forward(amplitude*2)
				t.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude*2)
				t2.left(90)
			elif(mode==3): #path should be inside curve
				t2.left(90)
				t2.forward(amplitude*2)
				t.set_position_point(t2.get_position())
				if (j==0):
					point0=t.get_position()
				t2.forward(-amplitude*2)
				t2.right(90)
			else:
				print("MODE ERROR")
				return
		else:
			if (mode==1):
				t2.right(90)
				t2.forward(amplitude)
				t.set_position_point(t2.get_position())
				t2.forward(-amplitude)
				t2.left(90)
			else:
				t.set_position_point(t2.get_position())

	# skin part of clay layer
	new_pattern_row = rotate_pattern(pattern_row,0,step_shift=-1)
	if (skin==True):
		for j in range (0,len(skin_points)):
			if (new_pattern_row[j]>.9):
				t.pendown()
				t.set_speed(speed)
			else:
				t.penup()
				t.set_speed(speed*2)
			t.set_position_point(skin_points[j])

	# if the curve is closed, close the curve
	if (slice0_closed==True):
		t.set_position_point(points[0])


	# check if there is any pattern on this row
	# if there is not, return
	if (pattern_check is False):
		# print("row with no pattern")
		return
	if (skip_glass is True):
		return

	t.penup()

	#pattern part of layer
	# t.set_extruder(1)

	# # woven pattern part of pattern layer
	# first_pattern_pixel = True
	# lpp = last_pattern_pixel(pattern_row)
	# for j in range(0,len(points)):
	# # for all points in slice
	# 	if (j<len(angles)): 
	# 		angle = angles[j]	

	# 	amplitude = (wall_width/2.0)/math.cos(math.radians(angle))
	# 	# amplitude = small_curve_check(slice0,amplitude,mode)

	# 	pattern_index = int(j*ratio)
	# 	if (pattern_row[pattern_index]>.9):
	# 		if (t.get_pen()==True): # if you are at the end of a pattern block
	# 			t.set_position_point(points[j])
	# 		# if (pattern_index>= lpp and lpp>0):
	# 		# 	break
	# 		t.penup()
	# 		amplitude=0
	# 		if (t.get_speed()==speed):
	# 			t.set_speed(speed*2)
	# 	else:
	# 		t.set_extruder(1) # has no effect if extruder is already 1
	# 		if (t.get_pen()==False): # if you are at the beginning of a pattern block
	# 			t.set_position_point(points[j])
	# 			if (first_pattern_pixel is True):
	# 				t.extrude(10) # extrude a little at very beginning of layer and pattern
	# 				first_pattern_pixel=False
	# 		t.pendown()
	# 		if (t.get_speed()>speed):
	# 			t.set_speed(speed)

	# 	t2.set_position_point(points[j])
	# 	if (offset==True):
	# 		o=j+1
	# 	else:
	# 		o=j
	# 	if (o%2==0):
	# 		if (mode==1): #path should be on curve
	# 			t2.left(90)
	# 			t2.forward(amplitude)
	# 			t.set_position_point(t2.get_position())
	# 			if (j==0):
	# 				point0=t.get_position()
	# 			t2.forward(-amplitude)
	# 			t2.right(90)
	# 		elif(mode==2): #path should be outside curve
	# 			t2.right(90)
	# 			t2.forward(amplitude*2)
	# 			t.set_position_point(t2.get_position())
	# 			if (j==0):
	# 				point0=t.get_position()
	# 			t2.forward(-amplitude*2)
	# 			t2.left(90)
	# 		elif(mode==3): #path should be inside curve
	# 			t2.left(90)
	# 			t2.forward(amplitude*2)
	# 			t.set_position_point(t2.get_position())
	# 			if (j==0):
	# 				point0=t.get_position()
	# 			t2.forward(-amplitude*2)
	# 			t2.right(90)
	# 		else:
	# 			print("MODE ERROR")
	# 			return
	# 	else:
	# 		if (mode==1):
	# 			t2.right(90)
	# 			t2.forward(amplitude)
	# 			t.set_position_point(t2.get_position())
	# 			t2.forward(-amplitude)
	# 			t2.left(90)
	# 		else:
	# 			t.set_position_point(t2.get_position())


	# # skin part of pattern layer
	# if (skin==True):
	# 	first_pattern_pixel = True
	# 	for j in range (0,len(skin_points)):
	# 		if (new_pattern_row[j]<=.9):
	# 			if (first_pattern_pixel):
	# 				if (j>0):
	# 					t.set_position_point(skin_points[j-1])
	# 				else:
	# 					t.set_position_point(skin_points[j])
	# 			t.pendown()
	# 			if (t.get_speed()>speed):
	# 				t.set_speed(speed)
	# 			if (first_pattern_pixel):
	# 				t.extrude(5)
	# 				first_pattern_pixel=False
	# 			t.set_position_point(skin_points[j])
	# 		else:
	# 			t.penup()
	# 			if (t.get_speed()==speed):
	# 				t.set_speed(speed*2)
	# 			first_pattern_pixel=True
	# 			t.set_position_point(skin_points[j])
	# t.penup()
	# t.lift(3)
	# t.set_speed(speed)
	# t.set_extruder(0)

	# don't weave pattern
	curve=rs.AddCurve(points)
	new_points = rs.DivideCurve(curve,len(pattern_row)-1)
	follow_curve_pattern_only(t, points=new_points, number_walls=1, pattern_row=pattern_row, reverse=reverse)

	

def weave_slice_pattern (t,pattern_array,shape,wall_width=3.0,wavelength=3.0, mode=1, bottom_layers=0, skin=False):
	t.write_gcode_comment("**************************************************")
	t.write_gcode_comment("******* file generated by WeaveSlicer ************")
	t.write_gcode_comment("******* conception: Camila Friedman-Gerlicz ******")
	t.write_gcode_comment("****** python implementation: Leah Buechley ******")
	t.write_gcode_comment("************** 2023 - present ********************")
	t.write_gcode_comment("**************************************************")
	layer_height = t.get_layer_height()
	shape_slices = slice_shape(shape,layer_height=layer_height)
	
	offset=True 
	layers = []
	points=False
	x=-1
	bottom_layer=False
	skin_points=[]
	if (skin is True):
		mode=3

	# for all slices in shape
	for i in range (0,len(shape_slices)-1):
	# for i in range (40,46):
		# print("layer: " +str(i))
		ratio = len(pattern_array)/len(shape_slices)
		pattern_index = int(round(i*ratio,0))
		print(i,pattern_index,len(pattern_array))
		if (pattern_index>5):
			pattern_index=pattern_index-3

		pattern_row=pattern_array[pattern_index] # get current row of pattern
		k=0
		# for all branches in current slice
		while (k<len(shape_slices[i])):
			slice0 = shape_slices[i][k] # current slice
			if (skin==True):
				skin_points = rs.DivideCurve(slice0,len(pattern_row))
				t.penup()
				slice0 = get_offset_curve(slice0,t.get_extrude_width()/2+.1)

			if (i<bottom_layers and rs.IsCurveClosed(slice0)):
				bottom_layer=[]
				point = rs.CurveAreaCentroid(slice0)[0]
				bottom_curve = slice0
				if (mode==1):
					bottom_curve = rs.OffsetCurve(slice0,point,wall_width)[0]
				elif(mode==3):
					bottom_curve = rs.OffsetCurve(slice0,point,wall_width*1.5)[0]
				else:
					bottom_curve = slice0
				bottom_curves=get_offset_curves(bottom_curve,t.get_extrude_width())
				bottom_layer = bottom_layer + [follow_curve(t,bottom_curve)]
				for c in range (0,len(bottom_curves)):
					bottom_layer = bottom_layer + [follow_curve(t,bottom_curves[c])]
					t.penup()

			if (len(shape_slices[i])==1):
				# if there is just one branch, use slice above to compute angles
				slice1 = shape_slices[i+1][k] # slice above
			else:
				# fail on more complex shape
				print("Can't apply pattern to complex shape!")
				return;

			points,points1,angles = find_points_and_angles(slice0,slice1,wavelength,wall_width=wall_width,mode=mode,layer=i)
			count=0
			while (angles[0]>85 and angles[0]<95 and count<5):
				# if the angle is close to 90
				# a co-planar slice was found
				# this is probably the wrong one, try to find a better one
				index = su.find_closest_slice(slice0,shape_slices[i+1]) 
				slice1 = shape_slices[i+1][index] # next slice
				points,points1,angles = find_points_and_angles(slice0,slice1,wavelength,wall_width=wall_width,mode=mode,layer=i)
				count+=1

			if (i>8 and i<len(shape_slices)-13):
				reverse=False
				if (i%2==0):
					reverse=True
				x=weave_points_and_angles_pattern(t,pattern_row,points,points1,angles,slice0,slice1,wall_width=wall_width,mode=mode,offset=offset, skin=skin, skin_points=skin_points, reverse=reverse)
			else:
				x=weave_points_and_angles(t,points,points1,angles,slice0,slice1,wall_width=wall_width,mode=mode,offset=offset)

			if (x==-1):
				print("error at index: " +str(i))
			else:
				if (i<bottom_layers and bottom_layer):
					layers.append(bottom_layer+[x])
				else:
					layers.append(x)
			t.pendown()
			k+=1
			
		offset=not(offset)

		if (rs.IsCurveClosed(slice1)==False or rs.IsCurveClosed(slice0)==False ): # if current or next curve is not closed, lift pen
			t.penup()

	# top slice
	if (points and points1 and angles):
		x=weave_points_and_angles(t,points,points1,angles,slice0,slice1,wall_width=wall_width,mode=mode,offset=offset)
		# x=weave_points_and_angles_pattern(t,pattern_row,points,points1,angles,slice0,slice1,wall_width=wall_width,mode=mode,offset=offset, skin=skin, skin_points=skin_points)
	if (x!=-1):
		layers.append(x)

	return layers

# Even walls no weaving
def even_wall_from_angles(t,angles,slice0,slice1,wall_width=3.0,top=False,steps=100):
	if (not(angles)):
		return -1

	if (top):
		slice0=slice1

	points = rs.DivideCurve(slice0, steps)

	t2 = ExtruderTurtle()
	t2.set_position_point(points[0])
	t2.set_position_point(points[1])
	t2.left(90)
	t2.forward(1)
	point = t2.get_position()
	t2.set_position_point(points[len(points)-1])

	slice0_closed = rs.IsCurveClosed(slice0)

	if (not(slice0_closed)):
		# open curve
		t.penup()
		t.set_position_point(points[0])
	else:
		# closed curve
		t.penup()
		t.set_position_point(points[0])
		t.pendown()
		
	# calculate number of walls for each point
	max_walls = 1
	walls = []
	for j in range(0,len(points)):
		# it is possible, if you're using angles from the prior slice 
		# that you have more points than you have angles
		# if this is the case, don't update the angle variable
		if (j<len(angles)): 
			angle = angles[j]	

		amplitude = (wall_width/2.0)/math.cos(math.radians(angle))
		amplitude = small_curve_check(slice0,amplitude,mode=3)

		number_walls = math.ceil(amplitude*2/t.get_extrude_width())
		# print("amplitude*2: " +str(round(amplitude,2)) + " number walls: " +str(number_walls))
		walls.append(number_walls)
		if (number_walls>max_walls):
			max_walls = number_walls

	# print("amplitude: " +str(round(amplitude,2)) + " max walls: " +str(max_walls))
	# actually generate path
	curve = slice0
	for w in range(1,max_walls+1):
		points = rs.DivideCurve(curve, steps)
		for j in range(0,len(points)):
			current_wall = walls[j]
			if (w<=current_wall):
				t.pendown()
			else:
				t.penup()
			t.set_position_point(points[j])

		# if the curve is closed, close the curve
		if (rs.IsCurveClosed(curve)==True):
			t.set_position_point(points[0])
		else:
			t.penup()
			t.set_position_point(points[0])
			t.pendown()

		# find next offset curve
		if (rs.IsCurveClosed(curve)==True):
			point = rs.CurveAreaCentroid(curve)[0]
		else:
			point = [0,0,0]
		next_curve = rs.OffsetCurve(curve,point,t.get_extrude_width())[0]
		curve = next_curve

def slice_even_walls (t,shape,wall_width=3.0,wavelength=3.0, bottom_layers=0):
	t.write_gcode_comment("**************************************************")
	t.write_gcode_comment("******* file generated by WeaveSlicer ************")
	t.write_gcode_comment("******* conception: Camila Friedman-Gerlicz ******")
	t.write_gcode_comment("****** python implementation: Leah Buechley ******")
	t.write_gcode_comment("************** 2023 - present ********************")
	t.write_gcode_comment("**************************************************")
	layer_height = t.get_layer_height()
	shape_slices = slice_shape(shape,layer_height=layer_height)
	# for all slices in shape
	offset=True 
	layers = []
	points=False
	x=-1
	bottom_layer=False
	for i in range (0,len(shape_slices)-1):
		k=0
		while (k<len(shape_slices[i])):
		# for all branches in current slice
			slice0 = shape_slices[i][k] # current slice

			if (i<bottom_layers and rs.IsCurveClosed(slice0)):
				bottom_layer=[]
				point = rs.CurveAreaCentroid(slice0)[0]
				bottom_curve = slice0
				if (mode==1):
					bottom_curve = rs.OffsetCurve(slice0,point,wall_width)[0]
				elif(mode==3):
					bottom_curve = rs.OffsetCurve(slice0,point,wall_width*1.5)[0]
				else:
					bottom_curve = slice0
				bottom_curves=get_offset_curves(bottom_curve,t.get_extrude_width())
				bottom_layer = bottom_layer + [follow_curve(t,bottom_curve)]
				for c in range (0,len(bottom_curves)):
					bottom_layer = bottom_layer + [follow_curve(t,bottom_curves[c])]
					t.penup()

			if (len(shape_slices[i])==1):
				# if there is just one branch, use slice above to compute angles
				slice1 = shape_slices[i+1][k] # slice above
			else:
				# if there is more than one branch, lift pen and find the slice above
				t.penup()
				# if a branch is closing there may not be a matching branch above
				if (len(shape_slices[i+1])>k):
				# if there is a matching branch above:
					# try easy guess first
					slice1 = shape_slices[i+1][k] # slice above
				else:
				# if there is no matching branch above
					# find closest slice because you have to
					index = su.find_closest_slice(slice0,shape_slices[i+1]) 
					slice1 = shape_slices[i+1][index] # next slice
			
			points,points1,angles = find_points_and_angles(slice0,slice1,wavelength,wall_width=wall_width,mode=mode)
			count=0
			while (angles[0]>85 and angles[0]<95 and count<5):
				# if the angle is close to 90
				# a co-planar slice was found
				# this is probably the wrong one, try to find a better one
				index = su.find_closest_slice(slice0,shape_slices[i+1]) 
				slice1 = shape_slices[i+1][index] # next slice
				points,points1,angles = find_points_and_angles(slice0,slice1,wavelength,wall_width=wall_width,mode=mode)
				count+=1

			x=even_wall_from_angles(t,angles,slice0,slice1,wall_width=wall_width)
			if (x==-1):
				print("error at index: " +str(i))
			else:
				if (i<bottom_layers and bottom_layer):
					layers.append(bottom_layer+[x])
				else:
					layers.append(x)
			t.pendown()
			k+=1
			
		offset=not(offset)

		if (rs.IsCurveClosed(slice1)==False or rs.IsCurveClosed(slice0)==False ): # if current or next curve is not closed, lift pen
			t.penup()

	# top slice
	if (points and points1 and angles):
		x=even_wall_from_angles(t,angles,slice0,slice1,wall_width=wall_width)
	if (x!=-1):
		layers.append(x)

	return layers

def even_wall_from_angles_pattern(t,pattern_row,angles,slice0,slice1,wall_width=3.0,top=False):
	if (not(angles)):
		return -1

	if (top):
		slice0=slice1

	steps = len(pattern_row)
	points = rs.DivideCurve(slice0, steps)
		
	# calculate number of walls for each point
	max_walls = 1
	walls = []
	pattern_check=False
	pattern_index = 0
	for j in range(0,len(points)):
		if (j<len(angles)): 
			angle = angles[j]	

		amplitude = (wall_width/2.0)/math.cos(math.radians(angle))
		amplitude = small_curve_check(slice0,amplitude,mode=3)

		number_walls = math.ceil(amplitude*2/t.get_extrude_width())
		# print("amplitude*2: " +str(round(amplitude,2)) + " number walls: " +str(number_walls))
		walls.append(number_walls)
		if (number_walls>max_walls):
			max_walls = number_walls
		if (pattern_row[j]<.5 and pattern_check==False):
			pattern_check = True
			first_pattern_index = j

	# print("amplitude: " +str(round(amplitude,2)) + " max walls: " +str(max_walls))
	# actually generate path

	# if there's no pattern on this layer
	# don't generate more points than necessary (1 per mm)
	if (pattern_check==False):
		resolution = 1.0
		points = rs.DivideCurveEquidistant(slice0, resolution)
		steps = len(points)
	else:
		curve_length = rs.CurveLength(slice0)
		if (curve_length/steps < .25):
			print("Warning!! Your pattern is very high resolution and could crash the print. Decrease the size of your array!")
			print("mm per pattern: " +str(round(curve_length/steps, 2)))

	# find all curves for layer
	curve = slice0
	offset_curves = []
	for w in range (0,max_walls):
		offset_curves.append(curve)
		if (rs.IsCurveClosed(curve)==True):
			point = rs.CurveAreaCentroid(curve)[0]
		else:
			point = [0,0,0]
		next_curve = rs.OffsetCurve(curve,point,t.get_extrude_width()*(1-w*.1))[0]		
		curve = next_curve
	offset_curves.reverse()

	# order curves: innder to outer walls but,
	# if there are more than 2 walls, do the second one first, to address collapse of inner wall 
	if (max_walls>2):
		new_offset_curves = []
		new_offset_curves.append(offset_curves[max_walls-2])
		for i in range(0,len(offset_curves)):
			if (i!=max_walls-2):
				new_offset_curves.append(offset_curves[i])
		offset_curves = new_offset_curves

	#clay part of layer
	speed=t.get_speed()
	curve = slice0
	for w in range(0,len(offset_curves)):
		t.penup()
		curve = offset_curves[w]
		points = rs.DivideCurve(curve, steps)
		first_pattern_pixel = True
		for j in range(0,len(points)):
			current_wall = walls[j]
			if (w<=current_wall and pattern_row[j]>.5):
				if (first_pattern_pixel):
					t.set_position_point(points[j])
					first_pattern_pixel=False
				t.pendown()
				t.set_speed(speed)
				t.set_position_point(points[j])
			else:
				t.penup()
				t.set_speed(speed*2)
				t.set_position(points[j].X, points[j].Y, points[j].Z+3)
				first_pattern_pixel=True

		# if the curve is closed, close the curve
		if (rs.IsCurveClosed(curve)==True and pattern_row[j]>.5):
			t.set_position_point(points[0])
		else:
			t.penup()

	# if there's no pattern on this layer, just return
	if (pattern_check==False):
		return

	#pattern part of layer
	t.lift(3)
	t.swap_extruder()
	curve = slice0
	for w in range(0,len(offset_curves)):
		t.penup()
		curve = offset_curves[w]
		points = rs.DivideCurve(curve, steps)
		first_pattern_pixel = True
		for j in range(1,len(points)-1):
			current_wall = walls[j]
			# pattern
			if (w<=current_wall and (pattern_row[j-1]<.5 or pattern_row[j]<.5 or pattern_row[j+1]<.5)):
				if (first_pattern_pixel):
					t.set_position_point(points[j])
				t.pendown()
				t.set_speed(speed/2)
				if (first_pattern_pixel):
					t.extrude(5)
					first_pattern_pixel=False
				t.set_position_point(points[j])
			# no pattern
			else:
				t.penup()
				t.set_speed(speed*2)
				first_pattern_pixel=True
				t.set_position(points[j].X, points[j].Y, points[j].Z+3)
		# if the curve is closed, close the curve
		if (rs.IsCurveClosed(curve)==True and pattern_row[0]<.5):
			t.set_position_point(points[0])
		else:
			t.penup()
			# t.set_position_point(points[0])
	t.set_speed(speed)
	t.lift(t.get_layer_height())
	t.swap_extruder()

def slice_even_walls_pattern (t,pattern,shape,wall_width=3.0,bottom_layers=0):
	t.write_gcode_comment("**************************************************")
	t.write_gcode_comment("******* file generated by WeaveSlicer ************")
	t.write_gcode_comment("******* conception: Camila Friedman-Gerlicz ******")
	t.write_gcode_comment("****** python implementation: Leah Buechley ******")
	t.write_gcode_comment("************** 2023 - present ********************")
	t.write_gcode_comment("**************************************************")
	layer_height = t.get_layer_height()
	shape_slices = slice_shape(shape,layer_height=layer_height)
	# for all slices in shape
	offset=True 
	layers = []
	points=False
	x=-1
	bottom_layer=False
	for i in range (0,len(shape_slices)-1):
		k=0
		ratio = len(pattern)/len(shape_slices)
		pattern_index = int(i*ratio)
		while (k<len(shape_slices[i])):
		# for all branches in current slice
			slice0 = shape_slices[i][k] # current slice

			if (i<bottom_layers and rs.IsCurveClosed(slice0)):
				bottom_layer=[]
				point = rs.CurveAreaCentroid(slice0)[0]
				bottom_curve = slice0
				bottom_curves=get_offset_curves(bottom_curve,t.get_extrude_width())
				bottom_layer = bottom_layer + [follow_curve(t,bottom_curve)]
				for c in range (0,len(bottom_curves)):
					bottom_layer = bottom_layer + [follow_curve(t,bottom_curves[c])]
					t.penup()

			if (len(shape_slices[i])==1):
				# if there is just one branch, use slice above to compute angles
				slice1 = shape_slices[i+1][k] # slice above
			else:
				# if there is more than one branch, lift pen and find the slice above
				t.penup()
				# if a branch is closing there may not be a matching branch above
				if (len(shape_slices[i+1])>k):
				# if there is a matching branch above:
					# try easy guess first
					slice1 = shape_slices[i+1][k] # slice above
				else:
				# if there is no matching branch above
					# find closest slice because you have to
					index = su.find_closest_slice(slice0,shape_slices[i+1]) 
					slice1 = shape_slices[i+1][index] # next slice
			
			points,points1,angles = find_points_and_angles(slice0,slice1,wavelength=2,wall_width=wall_width,mode=mode)
			count=0
			while (angles[0]>85 and angles[0]<95 and count<5):
				# if the angle is close to 90
				# a co-planar slice was found
				# this is probably the wrong one, try to find a better one
				index = su.find_closest_slice(slice0,shape_slices[i+1]) 
				slice1 = shape_slices[i+1][index] # next slice
				points,points1,angles = find_points_and_angles(slice0,slice1,wavelength=2,wall_width=wall_width,mode=mode)
				count+=1
			pattern_row = pattern[pattern_index]
			if (i>=bottom_layers):
				t.pendown()
				x=even_wall_from_angles_pattern(t,pattern_row,angles,slice0,slice1,wall_width=wall_width)
				if (x==-1):
					print("error at index: " +str(i))
				else:
					if (i<bottom_layers and bottom_layer):
						layers.append(bottom_layer+[x])
					else:
						layers.append(x)
			k+=1
		if (rs.IsCurveClosed(slice1)==False or rs.IsCurveClosed(slice0)==False ): # if current or next curve is not closed, lift pen
			t.penup()

		t.penup()
		t.lift(t.get_layer_height())	

	# top slice
	if (points and points1 and angles):
		x=even_wall_from_angles_pattern(t,pattern_row,angles,slice0,slice1,wall_width=wall_width)
	if (x!=-1):
		layers.append(x)

	return layers

